# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    path: '../resources/views/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
               # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entities,Helpers,System,var}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Http\:
        resource: '../src/Http'
        tags: ['controller.service_arguments']
        public: true


    filesystemLoader:
        class: \Twig\Loader\FilesystemLoader
        arguments: ['%path%']
    environment:
        class: \Twig\Environment
        arguments: ['@filesystemLoader']
    templateNameParser:
        class: Symfony\Component\Templating\TemplateNameParser
        arguments: []
    twigEngine:
        class: \Symfony\Bridge\Twig\TwigEngine
        arguments: ['@environment','@templateNameParser']
    App\System\View\IView:
        class: \App\System\View\View
        arguments: ['@twigEngine']
        public: true

    App\System\Config\IConfig:
        class: \App\System\Config\Config
        arguments: ['config']
        calls:
          - [ addConfigs, [["database.yaml", "app.yaml"]] ]
        public: true

    App\System\Database\Orm:
        class: \App\System\Database\Orm
        public: true


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
